---
- name: Iniciando instalación...
  debug:
    msg: "Iniciando instalación de paquetes"


- name: Instalación de Google Chrome
  debug:
    msg: "Iniciando instalación de Chrome"

- name: Does the Google apt file exist?
      command: test -f {{apt_file}}
      register: google_apt_exists
      ignore_errors: True

- name: Add Google Chrome key
      shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
      copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{apt_file}} owner=root group=root mode=644
      when: google_apt_exists.rc == 1

- name: Update apt cache
      apt: update_cache=yes
      when: google_apt_exists.rc == 1

- name: Install Google Chrome
      apt: pkg=google-chrome-stable state=installed

- name: Instalando paquetes adicionales
  apt: name={{ item }} state=latest
  with_items:
     - git
     - python
- name: Instalación de Spotify
  debug:
    msg: "Iniciando instalación de Spotify"

- name: Add apt keys
  apt_key: keyserver=keyserver.ubuntu.com id={{ item }}
  with_items:
    - 94558F59
    - D2C19886

- name: Add Apt Keys (2017-01)
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=BBEBDCB318AD50EC6865090613B00F1FD2C19886 state=present

- name: Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free'

- name: Install spotify
  apt: name=spotify-client update_cache=yes state=latest

